spring:

  datasource:
    url: jdbc:mysql://localhost:3306/bowwow?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: t!20110419
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      max-file-size: 10MB


logging:
  level:
    com.tutorial: debug

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa